app/landing/__init__.py
from flask import Blueprint

landing_bp = Blueprint('landing_bp', __name__)

from app.landing import routes

app/landing/routes.py
from flask import redirect, render_template, Response, request, g, url_for, current_app
from app.landing import landing_bp
from db_operations import get_group_info, get_single_thing, get_song_counts, list_all_things, record_upload, search_for_song, search_for_things, get_next_asset_id, get_song_names, update_track, list_things_on_date, add_new_song

import json, urllib
from uuid import UUID
from s3 import generate_presigned_post, get_metadata

@landing_bp.before_request
def translate_name():
    print(request.path)
    id = request.path.split('/')[1].lower()
    print(f'id: {id}')
    if id == 'ltbb':
        g.group_id = 0
    elif id == 'nice':
        g.group_id = 1
    elif id == '3rd': 
        g.group_id = 2
    elif id == 'm97ab':
        g.group_id = 3
    else:
        g.group_id = id

@landing_bp.route('/<raw_group_id>/search')
def search(raw_group_id):
    if request.args.get('tag'):
        return render_template(
            'search.html',
            group={'id': raw_group_id},
            things=search_for_things(request.args.get('tag', ''), g.group_id)
        )
    elif request.args.get('song'):
        return render_template(
            'search.html',
            group={'id': raw_group_id},
            things=search_for_song(request.args.get('song', ''), g.group_id)
        )
    else:
        return "Invalid search", 200


@landing_bp.route('/<raw_group_id>', methods=['GET'])
def home(raw_group_id):
    group_info = get_group_info(g.group_id)
    group_info = dict(zip(group_info.keys(), group_info))
    group_info['id'] = raw_group_id

    return render_template(
        'landing.html',
        group=group_info,
        things=list_all_things(g.group_id),
    )

@landing_bp.route('/<raw_group_id>/<record_date>', methods=['GET'])
def list_group_record_date(raw_group_id, record_date):
    group_info = get_group_info(g.group_id)
    group_info = dict(zip(group_info.keys(), group_info))
    group_info['id'] = raw_group_id

    return render_template(
        'landing.html',
        show_search=False,
        show_edit=False,
        group=group_info,
        song_counts=get_song_counts(g.group_id),
        things=list_things_on_date(g.group_id, record_date),
    )

@landing_bp.route('/<raw_group_id>/edit', methods=['GET'])
def edit(raw_group_id):

    ids_raw = map(lambda x: get_single_thing(x), request.args['filenames'].split(';'))
    id_dicts = []
    for id_raw in ids_raw:
        id = dict(id_raw)
        
        # Remove blank tags
        list_of_tags = [x for x in id['tags'].split(',') if x.strip() != '']

        if 'partial' in [x for x in list_of_tags]:
            list_of_tags.remove('partial')
            id['tags'] = ','.join(list_of_tags)
            id['partial'] = True
        else:
            id['partial'] = False
        id_dicts.append(id)

    return render_template(
        'edit.html',
        ids=id_dicts,
        group={ 'id': g.group_id },
        song_names=get_song_names(g.group_id)
    )

@landing_bp.route('/edit', methods=['POST'])
def save_edit():
    list(map(lambda x: update_track(**x), request.json))
    return '', 200


@landing_bp.route('/<raw_group_id>/songs')
def songs(raw_group_id):
    suggestions = get_song_names(g.group_id)

    open_suggestions = request.args.get('open_suggestions', "") != ""

    return render_template(
        "songs.html",
        group={ 'id': g.group_id },
        song_counts=get_song_counts(g.group_id),
        open_suggestions=open_suggestions,
        songs=suggestions
    )

@landing_bp.route('/<raw_group_id>/songs', methods=['POST'])
def create_song(raw_group_id):
    new_title = request.form['new-title'].strip()

    if add_new_song(g.group_id, new_title) == -1:
        return 'A song with this title already exists!', 302

    return redirect(url_for('landing_bp.songs', raw_group_id=raw_group_id, open_suggestions=True ))



@landing_bp.route('/<raw_group_id>/track/<track_id>')
def track(raw_group_id, track_id):
    track_obj = get_single_thing(track_id)
    return render_template(
        "track.html",
        group={ 'id': g.group_id },
        track_obj=track_obj
    )


@landing_bp.route('/info', methods=['GET'])
def info():
    text = 'This is the info route! Here is a kitten:'
    return render_template('info.html', content=text)


@landing_bp.route('/info', methods=['PUT'])
def update_info():
    return 'You have made a put request!'

@landing_bp.route('/<raw_group_id>/uploader')
def uploader(raw_group_id):
    return render_template(
        'uploader.html',
        group={ 'id': g.group_id },
    )


@landing_bp.route('/s3_upload_callback', methods = ['GET', 'POST', 'PUT'])
def sns():
    # TODO-Daniel: Verify Signature from Amazon to prevent malicious
    # AWS sends JSON with text/plain mimetype
    # TODO calculate e-tags client side and prevent duplicate uploads https://teppen.io/2018/06/23/aws_s3_etags/#what-is-an-s3-etag
    try:
        js = json.loads(request.data)
    except Exception as e:
        print("ERROR: An error occurred while parsing an SNS from Amazon! \n", e)

    hdr = request.headers.get('X-Amz-Sns-Message-Type', None)
    print(f'hdr: {hdr}')
    # subscribe to the SNS topic
    if hdr == 'SubscriptionConfirmation' and 'SubscribeURL' in js:
        # r = requests.get(js['SubscribeURL'])
        with urllib.request.urlopen(js['SubscribeURL']) as f:
            print(f.read().decode('utf-8'))

    if hdr == 'Notification':
        msg = js['Message']
        for r in json.loads(msg)['Records']:
            folder, file = r['s3']['object']['key'].split('/')

            # Grab the metadata that wasn't included in the SNS 
            metadata = get_metadata(r['s3']['object']['key'])
            guessed_date = metadata['ResponseMetadata']['HTTPHeaders'].get('x-amz-meta-guessed-folder-date', None)
            print(f'guessed date: {guessed_date}')
            
            record_upload(
                file,
                r['eventTime'],
                # r['requestParameters']['sourceIPAddress'],
                r['s3']['object']['size'],
                r['s3']['object']['eTag'],
                folder,
                record_date=guessed_date if guessed_date else '', 
                tags=f"AutoUpload-{guessed_date}" if guessed_date else ''
            )

    return 'OK\n'


@landing_bp.route('/next_asset_id', methods=['GET'])
def retrieve_next_asset_id():
    secret = request.args.get('secret')
    if not secret or secret != current_app.config['NEXT_ASSET_ID_SECRET']:
        return Response(json.dumps({"error": "Now just hold on a minute, bucko."}), status=401, mimetype="application/json")
    
    return json.dumps({'next_asset_id': get_next_asset_id()})
    


@landing_bp.route('/<raw_group_id>/upload/s3/params', methods=['GET'])
def get_presigned_s3_upload_url(raw_group_id):
    # https://github.com/transloadit/uppy/blob/main/packages/%40uppy/companion/src/server/controllers/s3.js
    # TODO-prod: Keep tracing of the user_facing_ids and validate if this is in the database. For now just see if it's a valid UUID
    try:
        print(f'metadata: {json.dumps(request.args)}')

        # uploader_name = request.args.get('metadata[uploader-name]')
        file_type = request.args.get('type')
    except ValueError as e:
        print(e)
        return Response(json.dumps({"error": "Now just hold on a minute, bucko."}), status=401, mimetype="application/json")

    params = request.args
    # Due to issues with how S3 encodes plus signs I'm just going to replace them with spaces for now.
    filename_with_folder = f'{g.group_id}/{get_next_asset_id()}_{params["filename"].replace("+", " ")}'
    
    fields = {
        # 'x-amz-meta-uploader-name': uploader_name,
        'Content-Type': file_type,
        'Cache-Control': "public, max-age=31536000, immutable"
    }

    x = generate_presigned_post(filename_with_folder, params['type'], fields)
    # x['fields']['content_type'] = file_type
    return json.dumps(x)

app/templates/_template.html
{% extends 'base.html' %}
{% from 'track_block.html' import track_block %}

{% block styles %}
<style>
</style>
{% endblock %}

{% block content %}
<h2 </h2>

<div>
</div>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="{{ url_for('static', filename='water.min.css')}}">
    <link rel='stylesheet' href="{{ url_for('static', filename='style.css') }}">
    <script data-goatcounter="https://audio.goatcounter.com/count" async src="//gc.zgo.at/count.js"></script>
    <script src="{{ url_for('static', filename='scripts.js') }}"></script>
    <script src="{{ url_for('static', filename='wavesurfer_6_6.js') }}"></script>

    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='apple-touch-icon.png') }}">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='favicon-32x32.png') }}">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='favicon-16x16.png') }}">

    <style>
        body {
            max-width: unset;
        }

        html,
        body {
            overflow-x: hidden
        }

        .apply-to-all {
            border-radius: 8px;
            background: var(--background-alt);
            padding: 16px 24px;
            margin-bottom: 12px;
        }

        .apply-to-all h2 {
            margin-top: 0;
        }
    </style>

    {% block extra_head %}
    {% endblock %}

    {% block styles %}
    {% endblock %}

</head>

<body style="margin: 0; padding: 0 0 100px 0; touch-action: none;">
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor"
        stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-play">
        <defs>
            <symbol id="play">
                <polygon points="5 3 19 12 5 21 5 3"></polygon>
            </symbol>
        </defs>
    </svg>
    <div
        style="width: 100vw; padding: 0; display: flex; flex-direction: row; justify-content: center; overflow-x: hidden;">
        <div style="{% block max_width %}max-width: 600px;{% endblock %} width:100%; ">
            <div style="display: flex; flex-direction: column; justify-content: space-between; align-items: center;">
                <nav style="align-self: flex-start;">
                    <a href="{{ url_for('landing_bp.home', raw_group_id=group.id) }}">Home</a>
                    <!-- <a style="margin-left: 50px;" href="/audio/{{ group.id }}/uploader">Upload</a> -->
                </nav>
                <!-- height: 95 to leave room for navigation -->
                <div style="width:95%; display: flex; flex-direction: column; align-content: center;">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>

            {% block static_audio_player %}
            <div id="audio_player"
                style="position: fixed;bottom: 0; bottom: calc(env(safe-area-inset-bottom)); touch-action: none;background-color: var(--background-body); width:100%; height: 100px; overflow-y:hidden; display: flex; flex-direction: row;flex: 1;">

                <button style="align-self: end;width:110px;flex-grow: 0;" type="button" class="btn btn-primary"
                    data-action="play" onclick="changeText()">
                    Play / Pause
                </button>
                <div style="height:200px; width:100%;flex-grow:1;" id="waveform"></div>
            </div>
            {% endblock %}
        </div>
    </div>
    </div>

    {% block scripts %}
    <script>

        const soundEffect = new Audio();
        soundEffect.autoplay = true;

        var wavesurfer = WaveSurfer.create({
            container: '#waveform',
            backend: 'MediaElement',
            barWidth: 3,
            barRadius: 3,
            cursorWidth: 1,
            height: 200,
            barGap: 3
        });

        // toggle play button
        document
            .querySelector('[data-action="play"]')
            .addEventListener(
                'click',
                wavesurfer.playPause.bind(wavesurfer)
            );

        wavesurfer.on('play', function (err) {

            document.querySelector('[data-action="play"]').innerText = "Pause";
        });
        wavesurfer.on('pause', function (err) {
            document.querySelector('[data-action="play"]').innerText = "Play";
        });
        wavesurfer.on('error', function (err) {
            console.log(err);
        });
        wavesurfer.on('ready', function () {
            <!-- iOS Safari does not allow programatic music playing -->
            if (navigator.userAgent.indexOf('Safari') != -1 && navigator.userAgent.indexOf('Chrome') == -1) {
                document.querySelector('[data-action="play"]').innerText = "Play";
            }
            else {
                document.querySelector('[data-action="play"]').innerText = "Play/Pause";
                wavesurfer.play();
            }
        });

        function changeText() {
            if (navigator.userAgent.indexOf('Safari') != -1 && navigator.userAgent.indexOf('Chrome') == -1) {
                document.querySelector('[data-action="play"]').innerText = "Play/Pause";
            }
        }

    </script>
    {% endblock %}
</body>

app/templates/edit.html
{% extends 'base.html' %}

{% block extra_head %}
<script type="text/javascript" src="{{ url_for('static', filename='fuzzyset.js') }}"></script>
{% endblock %}

{% block max_width %}
max-width: 800px;
{% endblock %}

{% block styles %}
<style>
    .apply-to-all {
        border-radius: 8px;
        background: var(--background-alt);
        padding: 16px 24px;
        margin-bottom: 12px;
    }
    .apply-to-all h2 {
        margin-top: 0;
    }

    .form-field {
        margin-bottom: 16px;
    }

    .id-edit-box{
        margin-bottom: 12px;
        border: 1px solid lightgrey;
        padding: 12px;
    }
    .id-edit-box h2{
        margin-top: 0px;
    }

    button {
        float: right;
        background-color: #0076d1;
        color: white;
    }

    button:hover{
        background-color: darkblue;
    }

    .skip-button {
        border: 2px solid #0076d1;
        color: #0076d1;
        background-color: white;
    }

    .clearfix:after {
        clear: both;
        content: ".";
        display: block;
        height: 0;
        visibility: hidden;
    }
    .clearfix {
        display: inline-block;
    }
    .clearfix {
        display: block;
    }
</style>
{% endblock %}

{% block scripts %}
<script>
    let fs = FuzzySet([
        {% for name in song_names %}
        "{{ name.name|safe }}",
        {% endfor %}
    ]);

    const els = document.getElementsByClassName('song_name');
    Array.from(els).forEach((el) => {
        if (el.title.trim() === ''){
            var tmp = fs.get(el.getAttribute('fallbackValue').split('_')[1]);
            if (tmp !== null){
                el.value = tmp[0][1];
            }
        }
    })

    function save() {
        const to_submit = [];
        const edited_tracks = document.getElementsByClassName("id-edit-box");

        for (const track of edited_tracks) {
            to_submit.push({
                id: document.querySelector(`#${track.id} .id`).value,
                title: document.querySelector(`#${track.id} .song_name`).value,
                recorded_by: document.querySelector(`#${track.id} .recorder`).value,
                location: document.querySelector(`#${track.id} .location`).value,
                description: document.querySelector(`#${track.id} .description`).value,
                date: document.querySelector(`#${track.id} .date`).value,
                tags: document.querySelector(`#${track.id} .tags`).value,
                partial: document.querySelector(`#${track.id} .partial`).checked,
            })
        }

        fetch(
            '{{ url_for("landing_bp.save_edit") }}', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify(to_submit),
            }
        ).then((response) => {
            if (response.ok) {
                document.getElementById('save_status').textContent = "Saved!"
                // window.location.href = '/{{ group.id }}/uploader';
            }
            else {
                document.getElementById('save_status').textContent = response.body;
            }
        });

        return false;
    }

    function apply_to_all() {
        const all_recorder = document.getElementById('all-recorder').value;
        const all_location = document.getElementById('all-location').value;
        const all_date = document.getElementById('all-date').value;
        const all_tags = document.getElementById('all-tags').value;

        if (all_recorder.trim() !== ''){
            for (const elem of document.getElementsByClassName("recorder")) {
                elem.value = all_recorder;
            }
        }

        if (all_location.trim() !== ''){
            for (const elem of document.getElementsByClassName("location")) {
                elem.value = all_location;
            }
        }

        if (all_date.trim() !== ''){
            for (const elem of document.getElementsByClassName("date")) {
                elem.value = all_date;
            }
        }

        if (all_tags.trim() !== ''){
            for (const elem of document.getElementsByClassName("tags")) {
                elem.value = all_tags;
            }
        }
    }
</script>
{% endblock %}

{% block content %}
<datalist id="song_names">
    {% for name in song_names %}
    <option value="{{ name.name }}">{{ name.name }}</option>
    {% endfor %}
</datalist>

<div class="apply-to-all">
    <h2>Apply to all</h2>
    <div style="display: flex; flex-direction: row; justify-content: space-between; flex-wrap: wrap;">
        <div class="form-field">
            <label for="recorder">Recorded By</label>
            <input id="all-recorder" type="text" name="recorder" placeholder="Louis Armstrong's iPhone"
               >
                <div>
                    <a onclick="document.getElementById('all-recorder').value = 'Wendy\'s Zoom';">Wendy's Zoom</a>,
                    <a onclick="document.getElementById('all-recorder').value = 'Daniel\'s iPhone';">Daniel's iPhone</a>,
                </div>
        </div>

        <div class="form-field">
            <label for="location">Recording location</label>
            <input id="all-location" type="text" name="location" placeholder="Culture Lab">
            <div>
                <a onclick="document.getElementById('all-location').value = 'Culture Lab';">Culture Lab</a>,
                <a onclick="document.getElementById('all-location').value = 'Chez Bushwick';">Chez Bushwick</a>,
                <a onclick="document.getElementById('all-location').value = 'Unknown';">Unknown</a>
            </div>
        </div>

        <div class="form-field">
            <label for="date">Recording Date</label>
            <input id="all-date" type="date" name="date">
        </div>

        <div class="form-field">
            <label for="tags">Tags</label>
            <input id="all-tags" type="text" name="tags">
            <div>
                <a onclick="document.getElementById('all-tags').value += 'Performance, ';">Performance</a>,
                <a onclick="document.getElementById('all-tags').value += 'Mashup, '">Mashup</a>
            </div>
        </div>
    </div>

    <button onclick="apply_to_all();">Apply to all</button>
    <div class="clearfix"></div>
</div>

<form onsubmit="event.preventDefault(); save();">
    {% for recording in ids %}
    <div id="track_{{ recording.id }}" class="id-edit-box" style="margin-bottom: 24px;">
        <h2>{{ recording.filename|unquote }}</h2>
        <input class="id" value="{{ recording.id }}" type="hidden">
        <div style="display: flex; flex-direction: row; justify-content: space-between; align-items: center;">
            <div class="">
                <label for="song_name">Song Name</label>
                    <input
                        title="{{ recording.title }}"
                        list="song_names"
                        class="song_name"
                        fallbackValue="{{ recording.filename|trim }}" 
                        value="{{ recording.title }}"
                        autocomplete="off"
                    >
            </div>

            <div style="max-width: 200px;">
                <label for="partial">Partial</label>
                <input
                    id="partial"
                    type="checkbox"
                    name="partial"
                    class="partial"
                    value="true"
                    autocomplete="off" {# Prevents Firefox from restoring checkbox state on refresh  #}
                    {% if recording['partial'] %}checked{% endif %}
                >
            </div>

            <div class="">
                <label for="tags">Tags</label>
                <input type="text" name="tags" class="tags" value="{{ recording.tags }}"  placeholder="sax solo, drum break">
            </div>

            {% if loop.nextitem is defined %}
            <div style="align-self: end;">
                <button type="button" class="skip-button" onclick="document.querySelector('#track_{{ loop.nextitem.id }}').scrollIntoView(); document.querySelector('#track_{{ loop.nextitem.id }} .song_name').focus();">Next -></button>
            </div>
            {% endif %}
        </div>
        <div style="width: 100%;">
            <label for="song_description">Description</label>
            <textarea style="width: 100%; height: 48px;" type="paragraph" class="description"
                placeholder="Experimental run in cut time.">{{ recording.description }}</textarea>
        </div>
        <div style="display: flex; flex-direction: row; justify-content: space-between;">
            <div class="">
                <label for="recorder">Recorded By</label>
                <input id="recorder" type="text" name="recorder" class="recorder" placeholder="Louis Armstrong's iPhone" value="{{ recording.recorded_by }}">
            </div>

            <div class="">
                <label for="location">Recording Location</label>
                <input id="location" type="text" name="location" class="location" placeholder="Culture Lab" value="{{ recording.location }}" >
            </div>

            <div class="">
                <label for="date">Recording Date</label>
                <input id="date" type="date" name="date" class="date" value="{{ recording.record_date }}">
            </div>
        </div>
    </div>
    {% endfor %}
    <div style="display: flex; flex-direction: column; align-items: end;">
        <button style="margin-left:auto;" type="submit">Save and next</button>
        <div style="color: green; width: fit-content;" id="save_status"></div>
    </div>
    <div class="clearfix"></div>
</form>

{% endblock %}

{% block static_audio_player %}
{% endblock %}

app/templates/home.html
{% extends 'base.html' %}
{% from 'track_block.html' import track_block %}

{% block styles %}
<style>
</style>
{% endblock %}

{% block content %}

<div>
</div>
{% endblock %}

app/templates/info.html
{% extends 'base.html' %}

{% block content %}
{{ content }}
<br>
<img src="{{ url_for('static', filename='kitten.jpg') }}">
{% endblock %}

app/templates/landing.html
{% extends 'base.html' %}
{% from 'track_block.html' import track_block %}

{% block styles %}
<style>
    .sticky-header {
        position: sticky;
        top: 0;
        background-color: var(--background-body);
        padding-bottom: 8px;
    }
</style>
{% endblock %}

{% block content %}
<h2>{{ group.name }}</h2>
<p>{{ group.description }}</p>


{% if show_search|default(True) %}
<div>
    <details>
        <summary>Search by Tag</summary>
        <ul>
            <li><a href="{{ url_for('landing_bp.search', raw_group_id=group.id) }}?tag=midi">Midi</a></li>
            <li><a href="{{ url_for('landing_bp.search', raw_group_id=group.id) }}?tag=draft">Draft</a></li>
            <li><a href="{{ url_for('landing_bp.search', raw_group_id=group.id) }}?tag=Performance">Performance</a></li>
            <li><a href="{{ url_for('landing_bp.search', raw_group_id=group.id) }}?tag=holiday">Holiday</a></li>
            <li><a href="{{ url_for('landing_bp.search', raw_group_id=group.id) }}?tag=session">Session</a></li>
            <li><a href="{{ url_for('landing_bp.search', raw_group_id=group.id) }}?tag=NOLA 2020">NOLA 2020</a></li>
            <li><a href="{{ url_for('landing_bp.search', raw_group_id=group.id) }}?tag=Preservation Hall">Preservation Hall</a></li>
            <li><a href="{{ url_for('landing_bp.search', raw_group_id=group.id) }}?tag=poor audio">Poor audio</a></li>
            <li><a href="{{ url_for('landing_bp.search', raw_group_id=group.id) }}?tag=cell phone recording">Cell phone recording</a></li>
            <li><a href="{{ url_for('landing_bp.search', raw_group_id=group.id) }}?tag=questionable title">Possibly incorrect title</a></li>
        </ul>
    </details>
</div>
{% endif %}

{% for date, recordings_by_date in things|groupby("record_date")|reverse %}
    <h3 id="{{date|trim}}" class="sticky-header" style="margin-bottom:0;">{{ date|trim }} <a href="{{ url_for('landing_bp.list_group_record_date', raw_group_id=group.id, record_date=date|trim) }}">🔗</a></h3>
    {% for location, recordings_by_date_and_loc in recordings_by_date|groupby("location") %}
        <h4 style="margin-top:0;">
            {{ location }}
            {% if show_edit|default(True) %}
            <a href="{{ url_for('landing_bp.edit', raw_group_id=group.id) }}?filenames={% for r_thing in recordings_by_date_and_loc|sort(attribute='filename') %}{{r_thing.filename|file_id}};{% endfor %}"> (edit all)</a>
            {% endif %}
        </h4>
        {% for r_thing in recordings_by_date_and_loc|sort(attribute="filename") %}
            {{ track_block(r_thing, group, show_edit|default(True)) }}
        {% endfor %}
    {% endfor %}
{% else %}
    <p>No recordings have been uploaded for this group yet! Go jam and then head over to the <a href="/audio/{{group.id}}/uploader">uploader</a>!</p>
{% endfor %}

{% endblock %}

app/templates/playlist.html
{% extends 'base.html' %}
{% from 'track_block.html' import track_block %}

{% block styles %}
<style>
</style>
{% endblock %}

{% block content %}
<h1>{{ playlist.title }}</h1>
<h2>{{ playlist.description }}</h2>
<div>{{ playlist.created_at }}</div>

<ul>
    {% for track in tracks %}
    {% if track is not none %}
    {{ track_block(track, group, show_edit, playlist_mode=True) }}
    {% endif %}
    {% endfor %}
</ul>

<div>
</div>
{% endblock %}

app/templates/track_block.html
{% macro track_block(thing, group, show_edit=True) -%}

<div
    id="{{ thing.filename|file_id }}"
    data-trackid="{{thing.filename|file_id}}"
    class="track-block"
    style="border: 1px solid var(--text-muted); padding: 8px 16px; margin-bottom: 12px; border-left: 4px solid {{ thing.record_date|date_to_color }};"
>
    <div style="width: 100%; display: flex; flex-direction: row; flex-wrap: wrap; justify-content: space-between;">
        <div>
            <a style="padding-right: 8px; display: flex; flex-direction: row;" onclick="changeTrack('{{ g.group_id }}/{{ thing.filename }}', wavesurfer)">
                <svg width="24" height="24"><use href="#play" fill="var(--links)" /></svg>
                <span>{% if thing.title != '' %} {{ thing.title }} {% else %} {{ thing.filename|unquote }} {% endif %}</span>
            </a>
            <div style="font-size: 10px;">{{ thing.filename.replace('+', ' ') }}</div>
            <div style="margin: 8px 0;">
                <i>{{ thing.description }}</i>
            </div>
        </div>

        <div style="display: flex; flex-direction: row; flex-wrap: wrap; margin-left: auto; height: fit-content;">
                        <a href="{{ url_for('landing_bp.search', raw_group_id=group.id) }}?song={{ thing.title }}" style="border: 1px solid black; padding: 4px 8px; border-radius: 4px;margin-right: 8px;">Search</a>
            <a href="https://audio-manager.s3.amazonaws.com/{{ g.group_id }}/{{thing.filename}}" style="border: 1px solid black; padding: 4px 8px; border-radius: 4px;margin-right: 8px;">⬇️</a>
            {% if show_edit %}
            <a target="_blank" href="{{ url_for('landing_bp.edit', raw_group_id=group.id) }}?filenames={{ thing.filename|file_id }}" style="border: 1px solid black; padding: 4px 8px; border-radius: 4px;">Edit</a>
            {% endif %}
        </div>
    </div>

    <div style="display: flex; flex-direction: row; flex-wrap: wrap; justify-content: space-between;"
        class="audio-player" id="{{ thing.filename }}">
    </div>
    <div style="display: flex; flex-direction: row; flex-wrap: wrap; justify-content: end;">
        <div style="font-style: italic;" class="tags">
            {% if thing.tags != '' %}
                {% for tag in thing.tags.strip().split(',') %}
                    <a href="{{ url_for('landing_bp.search', raw_group_id=group.id) }}?tag={{ tag|trim }}">{{ tag }}</a>,&nbsp;
                {% endfor %}
            {% endif %}
        </div>
        <div><a href="{{ url_for('landing_bp.home', raw_group_id=group.id) }}#{{ thing.record_date }}">{{ thing.record_date }}</a></div>
    </div>
</div>

{%- endmacro %}